# Generated by Django 5.2.9 on 2025-12-06 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=500)),
                ('house_type', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='House Description')),
                ('location', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('available', 'Available')], default='available', max_length=20)),
                ('price_per_night', models.FloatField()),
                ('offer', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
